
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensorpush:
  username: !secret sensorpush_login
  password: !secret sensorpush_password

sensor:
  - platform: sensorpush
  
frontend:
  themes: !include_dir_merge_named themes